[server]
headless = true
address = "0.0.0.0"
port = $PORT
maxUploadSize = 50

[browser]
serverAddress = true
serverPort = 10000
gatherUsageStats = false

[client]
showErrorDetails = false

[runner]
magicEnabled = false

[logger]
level = "error"